# Generated by Django 3.1 on 2022-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
